title: Mechstack
email: admin@mechstack.dev
description: Landing page for Mechstack, an LLC in Oklahoma created by Michael Smith.
baseurl: ""
url: "https://mechstack.dev"

title: Mechstack

content: Mechstack provides full-stack technology solutions.

# Add your social links
social:
  - platform: github
    url: https://github.com/smwa
  - platform: phone
    url: "tel: +1(405)929-0705"
  - platform: email
    url: "mailto: michael@mechstack.dev"

sharing_image: v4.1.png
google_analytics: "G-BB1MEQ4LM2"
half_side: right
